#!/usr/bin/env ruby
#  Copyright (C) 2007 Janico Greifenberg <jgre@jgre.org> and 
#  Dirk Kutscher <dku@tzi.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# $Id$

$:.unshift File.join(File.dirname(__FILE__), "../..", "lib")

require "event-loop/timer"

require "rdtnlog"
require "rdtnevent"
require "flutecl"
require "bundle"
require "optparse"

ppgDir = File.expand_path("ppgout")

opts = OptionParser.new do |opts|
  opts.on("-d", "--directory DIR", "Papageno incoming directory") do |dir|
    ppgDir = File.expand_path(dir)
  end

  opts.on("-s", "--flute-send EXECUTABLE", "Path to the flute-send executable") do |exec|
    ppgProg = File.expand_path(exec)
  end
end
args = ARGV.join(" ")
opts.parse!(ARGV)
begin
  Dir.mkdir(ppgDir)
rescue
end
fluteLink = FluteCL::FluteLink.new
fluteLink.open("flute0", args)

srcEid = "dtn://test/bla"
destEid = "dtn://oink/grunt"
RDTNConfig.instance.localEid = "dtn://bla.fasel"
bundle = Bundling::Bundle.new("mypayload", destEid, srcEid)
bundle.cosFlags = 1

2.seconds.from_now {fluteLink.sendBundle(bundle)}

EventLoop.run()
