#!/usr/bin/env ruby
#  Copyright (C) 2007 Janico Greifenberg <jgre@jgre.org> and 
#  Dirk Kutscher <dku@tzi.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

$:.unshift File.join(File.dirname(__FILE__))

require 'core'
require File.join(File.dirname(__FILE__), "..", "apps", "stateval", "eval2")

if $0 == __FILE__
  Dir.chdir(File.join(File.dirname(__FILE__), ".."))
  system("git commit -a")
  # get commit hash
  revision = IO.popen("git log -n1") {|p| p.read}
  dirName = File.join(Dir.getwd, 
			  "experiment#{Time.now.strftime('%Y%m%d-%H%M%S')}")
  fork do
    Sim::Core.new.run(dirName)
  end
  Process.waitall
  system("cp #{File.join(File.dirname(__FILE__), "eventdump")} #{dirName}")
  # write commit hash to dirName/revision
  open(File.join(dirName, "revision"), "w") do |f| 
    f.write(revision.to_s)
  end
  # run eval
  evalRun(dirName)
end
