#!/usr/bin/env ruby
# -*-ruby-*-

$:.unshift File.join(File.dirname(__FILE__), "../..", "lib")

require "clientapi"
require "clientlib"
require "clientregcl"

EventLoop.later do
  ri = RegInfo.new("dtn://my.dest")
  c=RdtnClient.new
  c.open("localhost",7777)
  c.register(ri)
  #b=Bundling::Bundle.new("test!", "dtn://my.dest")
  #c.sendBundle(b)
  #c.unregister(r)
  #c.close()
end


EventLoop.run

